CREATE TABLE Employee (
    EmployeeID INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    Email NVARCHAR(100),
    Phone NVARCHAR(15),
    HireDate DATETIME,
    DepartureDate DATETIME,
    Department NVARCHAR(50),
    Position NVARCHAR(50),
    Salary DECIMAL(10,2),
    CommissionRate DECIMAL(5,2),
    SalesTarget DECIMAL(10,2),
    AchievedSales DECIMAL(10,2) DEFAULT 0.00,
    ActiveStatus NVARCHAR(20),
    StreetAddress NVARCHAR(255),
    City NVARCHAR(100),
    State NVARCHAR(50),
    ZipCode NVARCHAR(15),
    Country NVARCHAR(50),
    HasHealthInsurance BIT,
    HasDentalInsurance BIT,
    HasRetirementPlan BIT
);
